name: Scan Multiple Repos

on:
  schedule:
    - cron: '0 2 * * *'  # Run daily at 2 AM UTC
  workflow_dispatch:  # Manual trigger

jobs:
  scan_repos:
    runs-on: ubuntu-latest
    steps:
    - name: Install Git
      run: sudo apt-get install git

    - name: Clone Repo 1
      run: |
        git clone https://github.com/dhiggins03/codeigniter
        cd codeigniter
        pip install checkov
        checkov -d .

    - name: Clone Repo 2
      run: |
        git clone https://github.com/dhiggins03/Juice-shop
        cd Juice-shop
        pip install checkov
        checkov -d .

    
