name: Scan Multiple Repos

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 2 * * *'  # Run daily at 2 AM UTC
  workflow_dispatch:  # Manual trigger

jobs:
  scan_repos:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: 
          - https://github.com/dhiggins03/Juice-shop
          - https://github.com/dhiggins03/codeigniter
          

    steps:
    - name: Checkout code from ${{ matrix.repo }}
      run: |
        git clone ${{ matrix.repo }}
        repo_name=$(basename -s .git ${{ matrix.repo }})
        cd $repo_name
        pip install checkov  # Or any other tool like Trivy, SonarQube, etc.
        checkov -d .
